#!/bin/bash
# ============================================================
# ShieldScan — Let's Encrypt SSL Setup
# Run AFTER deploy.sh, once your domain is pointing to this server.
#
# Usage:
#   sudo bash setup-ssl.sh
#
# What this script does:
#   1. Installs certbot
#   2. Stops Nginx temporarily to get the cert (standalone mode)
#   3. Issues a Let's Encrypt certificate for your domain
#   4. Copies cert to ./ssl/ for Nginx
#   5. Restarts Nginx with HTTPS
#   6. Sets up auto-renewal cron job
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC}   $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

INSTALL_DIR="${INSTALL_DIR:-/opt/shieldscan}"
ENV_FILE="$INSTALL_DIR/.env"

# ── Read domain ───────────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
    error "No .env found at $INSTALL_DIR/.env. Run deploy.sh first."
fi

DOMAIN=$(grep "^DOMAIN=" "$ENV_FILE" 2>/dev/null | cut -d= -f2)

if [ -z "$DOMAIN" ]; then
    read -rp "Enter your domain (e.g. shieldscan.duckdns.org): " DOMAIN
    echo "DOMAIN=${DOMAIN}" >> "$ENV_FILE"
fi

echo ""
echo "Getting Let's Encrypt certificate for: $DOMAIN"
echo ""

# ── Confirm DNS is pointing here ──────────────────────────────
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || curl -s icanhazip.com)
DOMAIN_IP=$(dig +short "$DOMAIN" 2>/dev/null | tail -1 || echo "unknown")

info "This server's IP: $SERVER_IP"
info "Domain resolves to: $DOMAIN_IP"

if [ "$SERVER_IP" != "$DOMAIN_IP" ]; then
    echo ""
    echo "  ⚠️  DNS mismatch detected."
    echo "     Go to duckdns.org and set your subdomain IP to: $SERVER_IP"
    echo "     Wait 2-3 minutes for DNS propagation, then re-run this script."
    echo ""
    read -rp "DNS is correct and propagated? Continue anyway? [y/N] " CONFIRM
    [[ "$CONFIRM" =~ ^[Yy]$ ]] || exit 1
fi

# ── Install certbot ───────────────────────────────────────────
if ! command -v certbot &>/dev/null; then
    info "Installing certbot..."
    apt-get update -qq
    apt-get install -y certbot
    success "certbot installed"
fi

# ── Stop Nginx to free port 80 for certbot standalone ─────────
info "Stopping Nginx temporarily..."
cd "$INSTALL_DIR"
docker compose stop nginx 2>/dev/null || true

# ── Issue certificate ─────────────────────────────────────────
info "Requesting certificate from Let's Encrypt..."
certbot certonly \
    --standalone \
    --non-interactive \
    --agree-tos \
    --email "admin@${DOMAIN}" \
    -d "$DOMAIN"

CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"

# ── Copy certs to ./ssl/ for Nginx ───────────────────────────
info "Copying certificates to $INSTALL_DIR/ssl/..."
cp "$CERT_DIR/fullchain.pem" "$INSTALL_DIR/ssl/cert.pem"
cp "$CERT_DIR/privkey.pem"   "$INSTALL_DIR/ssl/key.pem"
chmod 644 "$INSTALL_DIR/ssl/cert.pem"
chmod 600 "$INSTALL_DIR/ssl/key.pem"
success "Certificates installed"

# ── Restart Nginx ─────────────────────────────────────────────
info "Starting Nginx with HTTPS..."
docker compose start nginx

# ── Test HTTPS ────────────────────────────────────────────────
sleep 3
if curl -sf "https://${DOMAIN}/health" >/dev/null 2>&1; then
    success "HTTPS is working!"
else
    echo "  ⚠️  HTTPS test failed — check Nginx logs:"
    echo "      docker compose logs nginx"
fi

# ── Auto-renewal cron ─────────────────────────────────────────
info "Setting up auto-renewal cron job..."

RENEW_SCRIPT="$INSTALL_DIR/renew-ssl.sh"
cat > "$RENEW_SCRIPT" << EOF
#!/bin/bash
# Auto-generated by setup-ssl.sh
set -e
cd $INSTALL_DIR
docker compose stop nginx
certbot renew --standalone --quiet
cp /etc/letsencrypt/live/$DOMAIN/fullchain.pem $INSTALL_DIR/ssl/cert.pem
cp /etc/letsencrypt/live/$DOMAIN/privkey.pem   $INSTALL_DIR/ssl/key.pem
chmod 644 $INSTALL_DIR/ssl/cert.pem
chmod 600 $INSTALL_DIR/ssl/key.pem
docker compose start nginx
echo "SSL renewed at \$(date)" >> $INSTALL_DIR/logs/ssl-renewal.log
EOF
chmod +x "$RENEW_SCRIPT"

# Add cron: renew on the 1st and 15th of each month at 3am
CRON_JOB="0 3 1,15 * * bash $RENEW_SCRIPT"
( crontab -l 2>/dev/null | grep -v "renew-ssl"; echo "$CRON_JOB" ) | crontab -
success "Auto-renewal cron added (runs 1st and 15th of each month)"

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              HTTPS Setup Complete!                   ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Your app is now live at:  https://${DOMAIN}"
echo "  API docs:                 https://${DOMAIN}/docs"
echo "  Health check:             https://${DOMAIN}/health"
echo ""
echo "  Certificate expires in 90 days — auto-renewal is set up."
echo ""
